CREATE TABLE risk_review_flags (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id     BIGINT NOT NULL,
    risk_score_id   BIGINT NOT NULL,
    risk_score      DOUBLE PRECISION NOT NULL,
    primary_factor  VARCHAR(100) NOT NULL,
    flagged_by      UUID NOT NULL,
    status          VARCHAR(20) NOT NULL,
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    reviewed_at     TIMESTAMP(6) WITH TIME ZONE,
    reviewed_by     UUID,
    CONSTRAINT fk_risk_review_customer FOREIGN KEY (customer_id) REFERENCES customers (customer_id),
    CONSTRAINT fk_risk_review_score FOREIGN KEY (risk_score_id) REFERENCES risk_scores (id),
    CONSTRAINT fk_risk_review_flagged_by FOREIGN KEY (flagged_by) REFERENCES users (user_id),
    CONSTRAINT fk_risk_review_reviewed_by FOREIGN KEY (reviewed_by) REFERENCES users (user_id)
);

CREATE INDEX idx_risk_review_status_created ON risk_review_flags (status, created_at DESC);
CREATE UNIQUE INDEX uq_risk_review_one_pending_per_customer
    ON risk_review_flags (customer_id) WHERE status = 'PENDING';